# Generated by Django 4.1.2 on 2022-10-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='done',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.AddField(
            model_name='expense',
            name='sum',
            field=models.IntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='expense',
            name='categories',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='financeapp.category'),
            preserve_default=False,
        ),
    ]
