# Generated by Django 4.1.2 on 2022-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_remove_expense_done_remove_expense_name_expense_sum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='sum',
            field=models.IntegerField(),
        ),
    ]
