# Generated by Django 4.1.2 on 2022-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='category of username',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='category of username'),
        ),
    ]
