# Generated by Django 4.1.2 on 2022-10-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0005_remove_category_category of username_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='category of username',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user_id', 'name'), name='category of username'),
        ),
    ]
