# Generated by Django 4.1.2 on 2022-10-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeapp", "0006_remove_category_category of username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="category",
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ManyToManyField(to="financeapp.category"),
        ),
    ]
